#!/usr/bin/env python
# -*- coding: utf-8 -*- #
from __future__ import unicode_literals
import sys

PYTHON_VERSION = sys.version_info[0]

AUTHOR = u'Michelle Gill'
SITENAME = u'themodernscientist'

SITETITLE = 'themodernscientist'

SITEURL = '/Users/mlgill/Documents/blog/themodernscientist/output'

SITESUBTITLE = 'biophysicist, mac-unix zealot, pythonista'

PATH = 'content'
USE_FOLDER_AS_CATEGORY = False
# DEFAULT_DATE = 'fs'

### Time and date settings
TIMEZONE = 'America/New_York'
DEFAULT_LANG = u'en'
DEFAULT_DATE_FORMAT = '%Y/%m/%d'
ARTICLE_URL = 'posts/{date:%Y}/{date:%Y}-{date:%m}-{date:%d}-{slug}/'
ARTICLE_SAVE_AS = 'posts/{date:%Y}/{date:%Y}-{date:%m}-{date:%d}-{slug}/index.html'
YEAR_ARCHIVE_SAVE_AS = 'posts/{date:%Y}/index.html'
MONTH_ARCHIVE_SAVE_AS = None

### Feed settings
FEED_DOMAIN = 'http://themodernscientist.com'
FEED_DOMAIN_LINK = 'http://feedpress.me'
FEED_ATOM = None
FEED_RSS = 'feeds/main_rss.xml'
FEED_RSS_LINK = 'themodernscientist-rss'
FEED_ALL_ATOM = None
FEED_ALL_RSS = None
CATEGORY_FEED_ATOM = None
CATEGORY_FEED_RSS = None
TAG_FEED_ATOM = None
TAG_FEED_RSS = None
TRANSLATION_FEED_ATOM = None
TRANSLATION_FEED_RSS = None
FEED_EMAIL = 'https://feed.press/e/mailverify?feed_id=themodernscientist-rss'
FEED_USE_SUMMARY = True

## Generating files
DELETE_OUTPUT_DIRECTORY = False
OUTPUT_RETENTION = (".git")

## Blog post settings
SUMMARY_MAX_LENGTH = 50
DEFAULT_PAGINATION = 5

## Category and tag settings
USE_FOLDER_AS_CATEGORY = False
TAG_CLOUD_STEPS = 4
TAG_CLOUD_MAX_ITEMS = 100

## Theme settings
THEME = 'themes/octopress-theme_MLG'

PLUGIN_PATHS = ['../pelican_plugins']

PLUGINS = ['summary', 'latex', 'liquid_tags.img', 'liquid_tags.video',
           'liquid_tags.include_code', 'liquid_tags.notebook',
           'liquid_tags.literal', 'pelican_gist', 'tipue_search']

LATEX = 'article'

PYGMENTS_RST_OPTIONS = {'classprefix': 'pgcss', 'linenos': 'table'}

# This header file is automatically generated by the notebook plugin
EXTRA_HEADER = open('_nb_header_mod.html').read()
if PYTHON_VERSION < 3:
	EXTRA_HEADER = EXTRA_HEADER.decode('utf-8')

# Extra files
STATIC_PATHS = ['images', 'notebooks', 'notes',  
                'extra/favicon.png', 'extra/CNAME', 'extra/keybase.txt', 'extra/README.md', 'extra/Dockerfile']

EXTRA_PATH_METADATA = {'extra/favicon.png':{'path':'favicon.png'},
     	               'extra/CNAME':{'path':'CNAME'},
                       'extra/keybase.txt':{'path':'keybase.txt'},
                       'extra/README.md':{'path':'README.md'},
                       'extra/Dockerfile':{'path':'Dockerfile'},
                       }

ARTICLE_EXCLUDES = ['notes', 'themes', 'extra']
PAGE_PATHS = ['pages']

NOTEBOOK_DIR = 'notebooks'

DIRECT_TEMPLATES = ('index', 'archives', 'tags', 'search')

## Theme navbar settings
MENUITEMS = (('Archives', 'http://themodernscientist.com/archives.html'),)


DISPLAY_PAGES_ON_MENU = True

## Search and analytics
USE_GOOGLE_SEARCH = False
USE_TIPUE_SEARCH = True

## Theme sidebar settings
USE_CATEGORIES = False
SUBSCRIBE = True
SOCIAL = (('Twitter', 'http://www.twitter.com/modernscientist'),
          ('Github', 'https://github.com/mlgill'),
          ('Stack Overflow', 'http://stackoverflow.com/users/943044/mlgill'),
          ('LinkedIn', 'https://www.linkedin.com/in/michellelynngill'))




